# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8306b32b29e1c4736d2bcae11f144927142a2047cb79ccdf6c79369cbe85328970e518959a97f3d0d9566fb39f39eabea34f4eb138cbd85d1abb2c116d20f59

test:
  secret_key_base: 678bc534aec2d1088b32ea6e081e54ceea604ee8ef5f1ba54db1050c8f005b74c1caa9103fe8456c6001c9047dc39f8bfb49e53ed4ad331b6ce67345b82f5efa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
